[package]
name = "supermatrix"
version = "0.1.0"
authors = ["Abmatrix <http://www.abmatrix.org>"]
build = "build.rs"


[dependencies]
error-chain = "0.12"
node-cli = { path = "./cli" }
futures = "0.1"
ctrlc = { version = "3.0", features = ["termination"] }

[build-dependencies]
vergen = "2"