[package]
name = "abmatrix"
version = "0.1.0"
authors = ["Abmatrix <http://www.abmatrix.org>"]
build = "build.rs"
edition = "2018"

[dependencies]
error-chain = "0.12"
ctrlc = { version = "3.0", features = ["termination"] }
log = "0.4"
tokio = "0.1.7"
tokio-timer = "0.2"
futures = "0.1"
exit-future = "0.1"
hex-literal = "0.1"
parity-codec = { version = "3.2" }
sr-io = { git = "https://github.com/paritytech/substrate" }
client = { package = "substrate-client", git = "https://github.com/paritytech/substrate" }
primitives = { package = "substrate-primitives", git = "https://github.com/paritytech/substrate" }
inherents = { package = "substrate-inherents", git = "https://github.com/paritytech/substrate" }
basic_authorship = { package = "substrate-basic-authorship", git = "https://github.com/paritytech/substrate" }
substrate-service = { git = "https://github.com/paritytech/substrate" }
transaction-pool = { package = "substrate-transaction-pool", git = "https://github.com/paritytech/substrate" }
network = { package = "substrate-network", git = "https://github.com/paritytech/substrate" }
consensus = { package = "substrate-consensus-aura", git = "https://github.com/paritytech/substrate" }
grandpa = { package = "substrate-finality-grandpa", git = "https://github.com/paritytech/substrate" }
sr-primitives = { git = "https://github.com/paritytech/substrate" }
substrate-executor = { git = "https://github.com/paritytech/substrate" }
substrate-keystore = { git = "https://github.com/paritytech/substrate" }
substrate-cli = { git = "https://github.com/paritytech/substrate" }
substrate-telemetry = { package = "substrate-telemetry", git = "https://github.com/paritytech/substrate" }
vendor = { path = "./vendor" }
node-runtime = { path = "./runtime" }
signer = { path = "./vendor/signer" }

[build-dependencies]
vergen = "2"