[package]
name = "abmatrix"
version = "0.1.0"
authors = ["Abmatrix <http://www.abmatrix.org>"]
build = "build.rs"

[dependencies]
slog = "^2"
tokio = "0.1.7"
futures = "0.1"
serde_json = "1.0"
error-chain = "0.12"
ctrlc = { version = "3.0", features = ["termination"] }
exit-future = "0.1"
parking_lot = "0.4"
substrate-transaction-pool = { git = "https://github.com/paritytech/substrate" }
substrate-finality-grandpa = { git = "https://github.com/paritytech/substrate" }
substrate-basic-authorship = { git = "https://github.com/paritytech/substrate" }
substrate-consensus-aura = { git = "https://github.com/paritytech/substrate" }
substrate-primitives = { git = "https://github.com/paritytech/substrate" }
substrate-telemetry = { git = "https://github.com/paritytech/substrate" }
substrate-inherents = { git = "https://github.com/paritytech/substrate" }
substrate-keystore = { git = "https://github.com/paritytech/substrate" }
substrate-executor = { git = "https://github.com/paritytech/substrate" }
substrate-service = { git = "https://github.com/paritytech/substrate" }
substrate-network = { git = "https://github.com/paritytech/substrate" }
substrate-client = { git = "https://github.com/paritytech/substrate", default-features = false }
substrate-cli = { git = "https://github.com/paritytech/substrate" }
vendor = { path = "./vendor" }
node-runtime = { path = "./runtime" }
signer = { path = "./vendor/signer" }

[workspace]
members = [
    "runtime",
    "vendor",
]

[build-dependencies]
vergen = "2"